[type/__ssrq_ejabberd_server] Add --node-name parameter

diff --git a/type/__ssrq_ejabberd_server/gencode-remote b/type/__ssrq_ejabberd_server/gencode-remote
--- a/type/__ssrq_ejabberd_server/gencode-remote
+++ b/type/__ssrq_ejabberd_server/gencode-remote
@@ -27,6 +27,26 @@ breify() {
 	printf '%s' "$*" | sed -e 's/[].^$*\[]/\\&/g' -e 's:/:\\/:g'
 }
 
+
+read -r erl_node_is <"${__object:?}/explorer/node-name" || :
+read -r erl_node_should <"${__object:?}/parameter/node-name"
+
+if ! expr "${erl_node_should}" : '[^@]\{1,\}@.' >/dev/null
+then
+	printf 'Invalid --node-name: %s\n' "${erl_node_should}" >&2
+	printf 'It must be of the form node@hostname.\n' >&2
+	exit 1
+fi
+
+if test -n "${erl_node_is}" -a "${erl_node_is}" != "${erl_node_should}"
+then
+	printf \
+		'failure: the current Erlang node name is "%s", but should be "%s".\nThis process is currently not automated, please follow https://docs.ejabberd.im/admin/guide/managing/#change-computer-hostname manually, update %s and re-run cdist.' \
+		"${erl_node_is}" "${erl_node_should}" \
+		"${ejabberdctl_cfg_path:?}" >&2
+	exit 1
+fi
+
 if grep -q \
 	-e "^__file$(breify "${ejabberd_yml_path:?}")" \
 	-e "^__file$(breify "${ejabberdctl_cfg_path}")" \
