[type/__ssrq_ejabberd_user] Implement basic type

diff --git a/type/__ssrq_ejabberd_user/gencode-remote b/type/__ssrq_ejabberd_user/gencode-remote
--- a/type/__ssrq_ejabberd_user/gencode-remote
+++ b/type/__ssrq_ejabberd_user/gencode-remote
@@ -17,3 +17,53 @@
 # You should have received a copy of the GNU General Public License
 # along with cdist. If not, see <http://www.gnu.org/licenses/>.
 #
+
+quote() { printf '%s\n' "$*" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/'/"; }
+
+read -r state_is <"${__object:?}/explorer/state"
+read -r state_should <"${__object:?}/parameter/state"
+
+IFS=@ read -r username domain <<EOF
+${__object_id:?}
+EOF
+
+test -n "${username}" -a -n "${domain}" || {
+	echo '__object_id must be a JID of the form user@domain.' >&2
+	exit 1
+}
+
+test "${state_is}" != "${state_should}" || exit 0
+
+case ${state_should}
+in
+	(present)
+		password=$(cat "${__object:?}/parameter/password")
+
+		case ${state_is}
+		in
+			(absent)
+				cmd='register'
+				;;
+			(wrongpassword)
+				cmd='change_password'
+				;;
+			(*)
+				printf 'state_is: %s\n' "${state_is}" >&2
+				exit 1
+				;;
+		esac
+
+		printf 'ejabberdctl %s %s %s %s\n' \
+			"${cmd}" \
+			"$(quote "${username}")" "$(quote "${domain}")" \
+			"$(quote "${password}")"
+		;;
+	(absent)
+		printf 'ejabberdctl unregister %s %s\n' \
+			"$(quote "${username}")" "$(quote "${domain}")"
+		;;
+	(*)
+		printf 'Invalid --state: %s\n' "${state_should}" >&2
+		exit 1
+		;;
+esac
